from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class CodeAnalysisResult(BaseModel):
    """Structured analysis generated from a C# source file."""

    status: str = Field(default="ok")
    summary: str
    class_name: str | None = None
    methods: list[str] = Field(default_factory=list)
    dependencies: list[str] = Field(default_factory=list)
    security_metrics: dict[str, Any] = Field(default_factory=dict)


class DocumentationOutput(BaseModel):
    """Validated Markdown response generated by the documentation step."""

    markdown: str
    format: str = Field(default="markdown")


class ReadTextFileInput(BaseModel):
    """Input schema for reading a UTF-8 text file."""

    file_path: str


class WriteTextFileInput(BaseModel):
    """Input schema for writing UTF-8 text content to disk."""

    file_path: str
    content: str
